CREATE TABLE IF NOT EXISTS `printer` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `brand` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `price` float NOT NULL,
  `url` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `icc_file` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `functions` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `print_speed_black` float NOT NULL,
  `print_speed_color` float NOT NULL,
  `max_input_capacity` int(11) NOT NULL,
  `max_monthly_duty_cycle` int(11) NOT NULL,
  `auto_duplex` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `ink_cyan_price` float NOT NULL,
  `ink_cyan_yield` int(11) NOT NULL,
  `ink_magenta_price` float NOT NULL,
  `ink_magenta_yield` int(11) NOT NULL,
  `ink_yellow_price` float NOT NULL,
  `ink_yellow_yield` int(11) NOT NULL,
  `ink_black_price` float NOT NULL,
  `ink_black_yield` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;